version: "3.9"
services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    build:
      context: .
      args: 
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
      - MONGO_USER=admin
      - MONGO_PASSWORD=password
      - SESSION_SECRET=secret
    volumes:
      - ./:/app
    command: npm run dev

  mongo:
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

